version: '3'

services:
     nginx:
        container_name: nginx
        build: 
            context: requirements/nginx/.
            dockerfile: Dockerfile
        ports:
            - "443:443"
        restart: always
        volumes:
            - ~/data/wordpress:/var/www/wordpress
        networks:
            - inception
        depends_on:
            - "wordpress"
     mariadb:
        environment:
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_ADMIN_USER: ${DB_ADMIN_USER}
            DB_ADMIN_PASS: ${DB_ADMIN_PASS}
        container_name: mariadb
        build:
            context: requirements/mariadb/.
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ~/data/datab:/var/lib/mysql
        networks:
            - inception
     wordpress:
        environment:
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_ADMIN_USER: ${DB_ADMIN_USER}
            DB_ADMIN_PASS: ${DB_ADMIN_PASS} 
        container_name: wordpress
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ~/data/wordpress:/var/www/wordpress
        depends_on:
            - "mariadb"
        networks:
            - inception

networks:
    inception:
