version: '3'

services:
     nginx:
        container_name: nginx
        build: 
            context: requirements/nginx/.
            dockerfile: Dockerfile
        ports:
            - "443:443"
        restart: always
        volumes:
            - vol-wordpress:/var/www/wordpress
        networks:
            - inception
        depends_on:
            - "wordpress"
     mariadb:
        environment:
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_ADMIN_USER: ${DB_ADMIN_USER}
            DB_ADMIN_PASS: ${DB_ADMIN_PASS}
        container_name: mariadb
        build:
            context: requirements/mariadb/.
            dockerfile: Dockerfile
        restart: always
        volumes:
            - vol-database:/var/lib/mysql
        networks:
            - inception
     wordpress:
        environment:
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_ADMIN_USER: ${DB_ADMIN_USER}
            DB_ADMIN_PASS: ${DB_ADMIN_PASS} 
        container_name: wordpress
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        restart: always
        volumes:
            - vol-wordpress:/var/www/wordpress
        depends_on:
            - "mariadb"
        networks:
            - inception

networks:
    inception:

volumes:
  vol-wordpress:
    driver: local
    driver_opts:
      type: bind
      o: none
      device: ":/home/nferre/data/wordpress"
  vol-database:
    driver: local
    driver_opts:
      type: bind
      o: none
      device: ":/home/nferre/data/datab"

